# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogLogin(object):
    def setupUi(self, DialogLogin):
        DialogLogin.setObjectName("DialogLogin")
        DialogLogin.resize(450, 180)
        DialogLogin.setMinimumSize(QtCore.QSize(450, 180))
        DialogLogin.setMaximumSize(QtCore.QSize(650, 180))
        DialogLogin.setStyleSheet("QLabel, QCheckBox{\n"
"    color: white;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background-color: #22222e;\n"
"    border: 2px solid #f66867;\n"
"    border-radius: 30;\n"
"    color: white;\n"
"}\n"
"QDialog {\n"
"    background-color: #22222e;\n"
"}\n"
"\n"
"QPushButton {\n"
"    color: white;\n"
"    background-color: #fb5b5d;\n"
"    border-radius: 30;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #fa4244;\n"
"}")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(DialogLogin)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_login = QtWidgets.QLabel(DialogLogin)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_login.setFont(font)
        self.label_login.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_login.setObjectName("label_login")
        self.verticalLayout.addWidget(self.label_login)
        self.label_password = QtWidgets.QLabel(DialogLogin)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_password.setFont(font)
        self.label_password.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_password.setObjectName("label_password")
        self.verticalLayout.addWidget(self.label_password)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_login = QtWidgets.QLineEdit(DialogLogin)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_login.setFont(font)
        self.lineEdit_login.setText("")
        self.lineEdit_login.setMaxLength(30)
        self.lineEdit_login.setObjectName("lineEdit_login")
        self.verticalLayout_2.addWidget(self.lineEdit_login)
        self.lineEdit_password = QtWidgets.QLineEdit(DialogLogin)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_password.setFont(font)
        self.lineEdit_password.setMaxLength(60)
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.verticalLayout_2.addWidget(self.lineEdit_password)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.checkBox_view_password = QtWidgets.QCheckBox(DialogLogin)
        self.checkBox_view_password.setObjectName("checkBox_view_password")
        self.horizontalLayout_3.addWidget(self.checkBox_view_password)
        self.checkBox_save_password = QtWidgets.QCheckBox(DialogLogin)
        self.checkBox_save_password.setObjectName("checkBox_save_password")
        self.horizontalLayout_3.addWidget(self.checkBox_save_password)
        self.comboBox_save_password = QtWidgets.QComboBox(DialogLogin)
        self.comboBox_save_password.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBox_save_password.setObjectName("comboBox_save_password")
        self.horizontalLayout_3.addWidget(self.comboBox_save_password)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.pushButton_entry = QtWidgets.QPushButton(DialogLogin)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_entry.setFont(font)
        self.pushButton_entry.setObjectName("pushButton_entry")
        self.verticalLayout_3.addWidget(self.pushButton_entry)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(DialogLogin)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_register = QtWidgets.QLabel(DialogLogin)
        self.label_register.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_register.setFont(font)
        self.label_register.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_register.setStyleSheet("QLabel:active  {\n"
"  color: #497DDD; \n"
"}\n"
"QLabel{\n"
"  color: rgb(255, 0, 4)\n"
"}\n"
"")
        self.label_register.setObjectName("label_register")
        self.horizontalLayout_2.addWidget(self.label_register)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)

        self.retranslateUi(DialogLogin)
        QtCore.QMetaObject.connectSlotsByName(DialogLogin)

    def retranslateUi(self, DialogLogin):
        _translate = QtCore.QCoreApplication.translate
        DialogLogin.setWindowTitle(_translate("DialogLogin", "Вхід"))
        self.label_login.setText(_translate("DialogLogin", "Логін:"))
        self.label_password.setText(_translate("DialogLogin", "Пароль:"))
        self.lineEdit_login.setPlaceholderText(_translate("DialogLogin", "lebid"))
        self.lineEdit_password.setPlaceholderText(_translate("DialogLogin", "Pas$vv0rD"))
        self.checkBox_view_password.setText(_translate("DialogLogin", "Показати пароль"))
        self.checkBox_save_password.setText(_translate("DialogLogin", "Запам\'ятати пароль"))
        self.pushButton_entry.setText(_translate("DialogLogin", "Увійти"))
        self.label.setText(_translate("DialogLogin", "У вас немає облікового запису?"))
        self.label_register.setText(_translate("DialogLogin", "Зареєструватись"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogLogin = QtWidgets.QDialog()
    ui = Ui_DialogLogin()
    ui.setupUi(DialogLogin)
    DialogLogin.show()
    sys.exit(app.exec_())
