# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registration.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogRegistration(object):
    def setupUi(self, DialogRegistration):
        DialogRegistration.setObjectName("DialogRegistration")
        DialogRegistration.resize(500, 270)
        DialogRegistration.setMinimumSize(QtCore.QSize(500, 270))
        DialogRegistration.setMaximumSize(QtCore.QSize(900, 270))
        DialogRegistration.setStyleSheet("QDialog {\n"
"    background-color: #22222e;\n"
"}\n"
"\n"
"QPushButton {\n"
"    color: white;\n"
"    background-color: #fb5b5d;\n"
"    border-radius: 30;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #fa4244;\n"
"}")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(DialogRegistration)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget = QtWidgets.QWidget(DialogRegistration)
        self.widget.setStyleSheet("QLineEdit{\n"
"    background-color: #22222e;\n"
"    border: 2px solid #f66867;\n"
"    border-radius: 30;\n"
"    color: white;\n"
"}\n"
"\n"
"QLineEdit #lineEdit_user_name{\n"
"    border: 2px solid rgb(170, 170, 170);\n"
"}\n"
"\n"
"QLabel, QCheckBox{\n"
"    color: white;\n"
"}")
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_user_name = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_user_name.setFont(font)
        self.label_user_name.setStyleSheet("")
        self.label_user_name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_user_name.setObjectName("label_user_name")
        self.verticalLayout.addWidget(self.label_user_name)
        self.label_login = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_login.setFont(font)
        self.label_login.setStyleSheet("")
        self.label_login.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_login.setObjectName("label_login")
        self.verticalLayout.addWidget(self.label_login)
        self.label_password = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_password.setFont(font)
        self.label_password.setStyleSheet("")
        self.label_password.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_password.setObjectName("label_password")
        self.verticalLayout.addWidget(self.label_password)
        self.label_password_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_password_2.setFont(font)
        self.label_password_2.setStyleSheet("")
        self.label_password_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_password_2.setObjectName("label_password_2")
        self.verticalLayout.addWidget(self.label_password_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_user_name = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_user_name.setFont(font)
        self.lineEdit_user_name.setStyleSheet("")
        self.lineEdit_user_name.setText("")
        self.lineEdit_user_name.setMaxLength(30)
        self.lineEdit_user_name.setObjectName("lineEdit_user_name")
        self.verticalLayout_2.addWidget(self.lineEdit_user_name)
        self.lineEdit_login = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_login.setFont(font)
        self.lineEdit_login.setStyleSheet("")
        self.lineEdit_login.setMaxLength(30)
        self.lineEdit_login.setObjectName("lineEdit_login")
        self.verticalLayout_2.addWidget(self.lineEdit_login)
        self.lineEdit_password = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_password.setFont(font)
        self.lineEdit_password.setStyleSheet("")
        self.lineEdit_password.setMaxLength(60)
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.verticalLayout_2.addWidget(self.lineEdit_password)
        self.lineEdit_password_2 = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_password_2.setFont(font)
        self.lineEdit_password_2.setStyleSheet("")
        self.lineEdit_password_2.setMaxLength(60)
        self.lineEdit_password_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password_2.setObjectName("lineEdit_password_2")
        self.verticalLayout_2.addWidget(self.lineEdit_password_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_checkBox = QtWidgets.QHBoxLayout()
        self.horizontalLayout_checkBox.setObjectName("horizontalLayout_checkBox")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_checkBox.addItem(spacerItem)
        self.checkBox_view_password = QtWidgets.QCheckBox(self.widget)
        self.checkBox_view_password.setStyleSheet("")
        self.checkBox_view_password.setChecked(False)
        self.checkBox_view_password.setObjectName("checkBox_view_password")
        self.horizontalLayout_checkBox.addWidget(self.checkBox_view_password)
        self.checkBox_save_password = QtWidgets.QCheckBox(self.widget)
        self.checkBox_save_password.setObjectName("checkBox_save_password")
        self.horizontalLayout_checkBox.addWidget(self.checkBox_save_password)
        self.verticalLayout_3.addLayout(self.horizontalLayout_checkBox)
        self.pushButton_reg = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_reg.setFont(font)
        self.pushButton_reg.setStyleSheet("")
        self.pushButton_reg.setObjectName("pushButton_reg")
        self.verticalLayout_3.addWidget(self.pushButton_reg)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setStyleSheet("")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_log_in = QtWidgets.QLabel(self.widget)
        self.label_log_in.setMaximumSize(QtCore.QSize(160, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_log_in.setFont(font)
        self.label_log_in.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_log_in.setStyleSheet("QLabel:active  {\n"
"  color: #497DDD; \n"
"}\n"
"QLabel{\n"
"  color: rgb(255, 0, 4)\n"
"}\n"
"")
        self.label_log_in.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_log_in.setObjectName("label_log_in")
        self.horizontalLayout_2.addWidget(self.label_log_in)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addWidget(self.widget)

        self.retranslateUi(DialogRegistration)
        QtCore.QMetaObject.connectSlotsByName(DialogRegistration)

    def retranslateUi(self, DialogRegistration):
        _translate = QtCore.QCoreApplication.translate
        DialogRegistration.setWindowTitle(_translate("DialogRegistration", "Реєстрація користувача"))
        self.label_user_name.setText(_translate("DialogRegistration", "Ім\'я користувача:"))
        self.label_login.setText(_translate("DialogRegistration", "Логін:"))
        self.label_password.setText(_translate("DialogRegistration", "Пароль:"))
        self.label_password_2.setText(_translate("DialogRegistration", "Підтвердження пароля"))
        self.lineEdit_user_name.setPlaceholderText(_translate("DialogRegistration", "user_name"))
        self.lineEdit_login.setPlaceholderText(_translate("DialogRegistration", "login"))
        self.lineEdit_password.setPlaceholderText(_translate("DialogRegistration", "Pas$vv0rD"))
        self.lineEdit_password_2.setPlaceholderText(_translate("DialogRegistration", "Pas$vv0rD"))
        self.checkBox_view_password.setText(_translate("DialogRegistration", "Показати пароль"))
        self.checkBox_save_password.setText(_translate("DialogRegistration", "Запам\'ятати пароль"))
        self.pushButton_reg.setText(_translate("DialogRegistration", "Реєстрація"))
        self.label.setText(_translate("DialogRegistration", "Вже є обліковий запис?"))
        self.label_log_in.setText(_translate("DialogRegistration", "Увійти"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogRegistration = QtWidgets.QDialog()
    ui = Ui_DialogRegistration()
    ui.setupUi(DialogRegistration)
    DialogRegistration.show()
    sys.exit(app.exec_())
